default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "password" } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") { "my_training_log_development" } %>

test:
  <<: *default
  database: my_training_log_test

production:
  url: <%= ENV["DATABASE_URL"] %>
